version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: 'postgres'
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 5000:15672

  redis:
    image: redis:latest
    container_name: 'redis'
    restart: always
    ports:
      - 6379:6379
    command: redis-server

  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3.10-bullseye
    container_name: 'sistema'
    volumes:
      - ..:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode
    ports:
      - 8000:8000

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    depends_on:
      - postgres
      - rabbitmq
      - redis

volumes:
  postgres-data: null
